config/routes.rb
Rails.application.routes.draw do
  resources :talings
  get 'post/index'
  root 'post#index'
  get 'post/new'
  get 'post/read/:id_post' => 'post#read'
  post 'post/create'

end

app/models/memo.rb
class Memo < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/taling.rb
class Taling < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    # @posts 
    @all_post = Post.all
  end

  def new
  end

  def create
    Post.create(title: params[:new_title_input], content: params[:new_content_input])
    # pos = Post.new
    # pos.title = params[:new_title_input]
    # pos.content = params[:new_content_input]
    # pos.save
    redirect_to "/post/index"
  end
  
  def read
    @one_post = Post.find(params[:id_post])
    @one_post.view = @one_post.view + 1
    @one_post.save
  end
end

app/controllers/talings_controller.rb
class TalingsController < ApplicationController
  before_action :set_taling, only: [:show, :edit, :update, :destroy]

  # GET /talings
  # GET /talings.json
  def index
    @talings = Taling.all
  end

  # GET /talings/1
  # GET /talings/1.json
  def show
  end

  # GET /talings/new
  def new
    @taling = Taling.new
  end

  # GET /talings/1/edit
  def edit
  end

  # POST /talings
  # POST /talings.json
  def create
    @taling = Taling.new(taling_params)

    respond_to do |format|
      if @taling.save
        format.html { redirect_to @taling, notice: 'Taling was successfully created.' }
        format.json { render :show, status: :created, location: @taling }
      else
        format.html { render :new }
        format.json { render json: @taling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talings/1
  # PATCH/PUT /talings/1.json
  def update
    respond_to do |format|
      if @taling.update(taling_params)
        format.html { redirect_to @taling, notice: 'Taling was successfully updated.' }
        format.json { render :show, status: :ok, location: @taling }
      else
        format.html { render :edit }
        format.json { render json: @taling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talings/1
  # DELETE /talings/1.json
  def destroy
    @taling.destroy
    respond_to do |format|
      format.html { redirect_to talings_url, notice: 'Taling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taling
      @taling = Taling.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taling_params
      params.require(:taling).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/talings_helper.rb
module TalingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/post/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>
<h2>게시물이 작성되었습니다.</h2>
<a href="/">전체게시물 보러가기</a>

app/views/post/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>
<h2>모든 게시물 보기</h2>
<a href="/post/new">게시물 작성</a>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">제목</th>
      <th scope="col">내용</th>
      <th scope="col">조회수</th>
    </tr>
  </thead>
  <tbody>
    <% @all_post.each do |post| %> 
    <tr>
      <th scope="row"><%=post.id%></th>
      <td><a href="/post/read/<%=post.id%>"><%=post.title%></a></td>
      <td><%=post.content%></td>
      <td><%=post.view%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/post/new.html.erb
<h1>Post#new</h1>
<p>Find me in app/views/post/new.html.erb</p>

<div class="container">
    <h2>글 작성</h2>
    <form action='/post/create' method="post">
      <div class="form-group">
        <label for="exampleFormControlInput1">제목</label>
        <input type="text" name="new_title_input" class="form-control" id="exampleFormControlInput1" placeholder="제목을 입력해주세요">
      </div>
      
      
      <div class="form-group">
        <label for="exampleFormControlTextarea1">내용</label>
        <textarea class="form-control" name="new_content_input" id="exampleFormControlTextarea1" rows="3"></textarea>
      </div>
      <button type="submit" class="btn btn-success">작성하기</button>
    </form>
</div>

app/views/post/read.html.erb
<h1>Post#read</h1>
<p>Find me in app/views/post/read.html.erb</p>
<div class="container">
    <p style="font-size:30px">제목: <%=@one_post.title %></p>
    <hr>
    <p>내용: <span style="float:right">조회수: <%=@one_post.view%></span></p>
    <%= @one_post.content %>
</div>

app/views/talings/_form.html.erb
<%= form_for(@taling) do |f| %>
  <% if @taling.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taling.errors.count, "error") %> prohibited this taling from being saved:</h2>

      <ul>
      <% @taling.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talings/edit.html.erb
<h1>Editing Taling</h1>

<%= render 'form' %>

<%= link_to 'Show', @taling %> |
<%= link_to 'Back', talings_path %>

app/views/talings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Talings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @talings.each do |taling| %>
      <tr>
        <td><%= taling.title %></td>
        <td><%= taling.content %></td>
        <td><%= link_to 'Show', taling %></td>
        <td><%= link_to 'Edit', edit_taling_path(taling) %></td>
        <td><%= link_to 'Destroy', taling, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taling', new_taling_path %>

app/views/talings/new.html.erb
<h1>New Taling</h1>

<%= render 'form' %>

<%= link_to 'Back', talings_path %>

app/views/talings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @taling.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @taling.content %>
</p>

<%= link_to 'Edit', edit_taling_path(@taling) %> |
<%= link_to 'Back', talings_path %>